# Generated by Django 4.1.2 on 2022-10-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['album']},
        ),
    ]
