# Generated by Django 4.1.2 on 2022-10-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0002_alter_track_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='DRF.album'),
        ),
    ]
