# Generated by Django 4.1.2 on 2022-10-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0003_alter_track_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Album', to='DRF.album'),
        ),
    ]
