# Generated by Django 4.1.2 on 2022-10-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0003_alter_track_album'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('album',)},
        ),
        migrations.RemoveField(
            model_name='track',
            name='order',
        ),
    ]
