# Generated by Django 4.1.2 on 2022-10-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0004_alter_track_unique_together_remove_track_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
    ]
