# Generated by Django 4.1.2 on 2022-10-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0005_alter_track_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
