# Generated by Django 4.1.2 on 2022-10-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0005_alter_track_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
    ]
