# Generated by Django 4.1.2 on 2022-10-30 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0006_alter_track_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name']},
        ),
    ]
