# Generated by Django 4.1.2 on 2022-10-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0007_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['artist']},
        ),
    ]
