# Generated by Django 4.1.2 on 2022-10-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0007_alter_track_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
    ]
