# Generated by Django 4.1.2 on 2022-10-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0008_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
    ]
