# Generated by Django 4.1.2 on 2022-10-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0010_artist_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='order',
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
