# Generated by Django 4.1.2 on 2022-10-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0011_remove_track_order_alter_artist_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='track',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('album', 'order')},
        ),
    ]
