# Generated by Django 4.1.2 on 2022-10-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0012_alter_track_options_track_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='track',
            name='order',
        ),
    ]
