# Generated by Django 4.1.2 on 2022-10-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0013_alter_track_options_alter_track_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='track',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('album', 'order')},
        ),
    ]
