# Generated by Django 4.1.2 on 2022-10-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0014_alter_track_options_track_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='album',
            name='track',
            field=models.ManyToManyField(to='DRF.track'),
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='track',
            name='order',
        ),
    ]
